/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MarkBookApp;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author khalil
 */
public class AddFinalMarks extends javax.swing.JInternalFrame {

    //CREATE GLOBAL VARIABLES
    Connection con;
    Statement stmt;
    ResultSet rs;
    /**
     * Creates new form AddFinalMarks
     */
    public AddFinalMarks() {
        initComponents();
        getContentPane().setBackground(new Color(0, 105, 255));
        DoConnect();
    }

    public void DoConnect(){
        
        try{
            //CONNECT TO DATABASE
            String user = "tutor";
            String password = "tutorAdmin";
            String url = "jdbc:derby://localhost:1527/students";
            
            con = DriverManager.getConnection(url, user, password);
            
            //EXECUTE SOME SQL AND LOAD THE RECORDS INTO THE RESULT SET
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT * FROM coursemarks";
            rs = stmt.executeQuery(sql);
            
            //SET CURSOR
            rs.first();
            
            //GET DATA FROM RESULTSET
            int id = rs.getInt(1);
            String firstName = rs.getString(2);
            String lastName = rs.getString(3);
            
            String sID = String.valueOf(id);
            //DISPLAY RECORDS TO THE TEXTFIELDS
            txtID.setText(sID);
            txtFirst.setText(firstName);
            txtLast.setText(lastName);
            txtTest1.setText(Double.toString(rs.getDouble(4)));
            txtTest2.setText(Double.toString(rs.getDouble(5)));
            txtAssignment.setText(Double.toString(rs.getDouble(6)));
            txtProject.setText(Double.toString(rs.getDouble(7))); 
                        
        }
        catch(SQLException e){ //CREATES OBJECT CALLED "E"
            JOptionPane.showMessageDialog(AddFinalMarks.this, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTest1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTest2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAssignment = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProject = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmdFirst = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmdLast = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmdUpdate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmdClose = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        cmdPrev = new javax.swing.JButton();
        txtFirst = new javax.swing.JTextField();
        cmdNext = new javax.swing.JButton();
        txtLast = new javax.swing.JTextField();
        paper1 = new javax.swing.JTextField();
        paper2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("ID:");

        jLabel2.setText("First Name:");

        txtTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTest2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name:");

        jLabel4.setText("Test1:");

        jLabel5.setText("Test2:");

        cmdFirst.setText("First");
        cmdFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFirstActionPerformed(evt);
            }
        });

        jLabel6.setText("Assignment Mark:");

        cmdLast.setText("Last");
        cmdLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLastActionPerformed(evt);
            }
        });

        jLabel7.setText("Project Mark:");

        cmdUpdate.setText("Update");
        cmdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateActionPerformed(evt);
            }
        });

        jLabel8.setText("Add Final Marks");

        cmdClose.setText("Close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        cmdPrev.setText("Previous");
        cmdPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrevActionPerformed(evt);
            }
        });

        cmdNext.setText("Next");
        cmdNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNextActionPerformed(evt);
            }
        });

        jLabel9.setText("Paper1:");

        jLabel10.setText("Paper2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9))
                                        .addGap(60, 60, 60))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel5))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(jLabel10)))
                                        .addGap(54, 54, 54)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAssignment)
                                    .addComponent(txtLast)
                                    .addComponent(txtFirst)
                                    .addComponent(txtTest1)
                                    .addComponent(txtTest2)
                                    .addComponent(txtProject)
                                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(paper1)
                                    .addComponent(paper2))))
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdFirst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdPrev)
                                .addGap(18, 18, 18)
                                .addComponent(cmdNext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdLast))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(cmdUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(cmdClose)))
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paper1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paper2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdFirst)
                    .addComponent(cmdLast)
                    .addComponent(cmdPrev)
                    .addComponent(cmdNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdUpdate)
                    .addComponent(cmdClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTest2ActionPerformed

    private void cmdFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFirstActionPerformed
        //GET DATA FROM RESULTSET
        try{
            rs.first();

            txtID.setText(Integer.toString(rs.getInt("id")));
            txtFirst.setText(rs.getString("first_name"));
            txtLast.setText(rs.getString("last_name"));
            txtTest1.setText(Double.toString(rs.getDouble("test1")));
            txtTest2.setText(Double.toString(rs.getDouble("test2")));
            txtAssignment.setText(Double.toString(rs.getDouble("assignment")));
            txtProject.setText(Double.toString(rs.getDouble("project")));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(AddFinalMarks.this, e.getMessage());
        }
    }//GEN-LAST:event_cmdFirstActionPerformed

    private void cmdLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLastActionPerformed
        //GET DATA FROM RESULTSET AND ADD TO TEXT FIELDS
        try{
            rs.last();

            txtID.setText(Integer.toString(rs.getInt(1)));
            txtFirst.setText(rs.getString(2));
            txtLast.setText(rs.getString(3));
            txtTest1.setText(Double.toString(rs.getDouble(4)));
            txtTest2.setText(Double.toString(rs.getDouble(5)));
            txtAssignment.setText(Double.toString(rs.getDouble(6)));
            txtProject.setText(Double.toString(rs.getDouble(7)));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(AddFinalMarks.this, e.getMessage());
        }
    }//GEN-LAST:event_cmdLastActionPerformed

    private void cmdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateActionPerformed
        //GET DATA FROM FIELDS AND VALIDATE IT
        double test1 = 0.0;
        double test2 = 0.0;
        double assignment = 0.0;
        double project = 0.0;

        boolean valid = true;

        try{
            test1 = Double.parseDouble(txtTest1.getText());
            test2 = Double.parseDouble(txtTest1.getText());
            assignment = Double.parseDouble(txtAssignment.getText());
            project = Double.parseDouble(txtProject.getText());
        }
        catch(NumberFormatException err){
            JOptionPane.showMessageDialog(AddFinalMarks.this, "Must enter a number", "MarkBook", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }

        if(valid){
            try{
                //UPDATE ROWS
                rs.updateDouble("test1", test1);
                rs.updateDouble("test2", test2);
                rs.updateDouble("assignment", assignment);
                rs.updateDouble("project", project);

                rs.updateRow();

                //SHOW SUCCESS MESSAGE
                JOptionPane.showMessageDialog(AddFinalMarks.this, "Successfully updated the record", "MarkBook", JOptionPane.INFORMATION_MESSAGE);
                cmdNextActionPerformed(evt);
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(AddFinalMarks.this, e.getMessage());
            }
        }

        else{
            //CLEAR FIELDS
            txtTest1.setText("");
            txtTest2.setText("");
            txtAssignment.setText("");
            txtProject.setText("");
        }

    }//GEN-LAST:event_cmdUpdateActionPerformed

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        //
        try{
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(AddFinalMarks.this, e.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void cmdPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrevActionPerformed
        //GET DATA FROM RESULT SET
        try{
            if(rs.previous()){
                txtID.setText(Integer.toString(rs.getInt("id")));
                txtFirst.setText(rs.getString("first_name"));
                txtLast.setText(rs.getString("last_name"));
                txtTest1.setText(Double.toString(rs.getDouble("test1")));
                txtTest2.setText(Double.toString(rs.getDouble("test2")));
                txtAssignment.setText(Double.toString(rs.getDouble("assignment")));
                txtProject.setText(Double.toString(rs.getDouble("project")));

            }
            else{
                rs.next();
                JOptionPane.showMessageDialog(AddFinalMarks.this, "You have reached the begginning of the file", "MarkBook",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(AddFinalMarks.this, e.getMessage());
        }

    }//GEN-LAST:event_cmdPrevActionPerformed

    private void cmdNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNextActionPerformed
        //GO TO NEXT ROW
        try{

            if(rs.next()){
                //GET DATA FROM RESULT SET and DISPLAY DATA IN TEXT FIELDS
                txtID.setText(Integer.toString(rs.getInt(1)));
                txtFirst.setText(rs.getString(2));
                txtLast.setText(rs.getString(3));
                txtTest1.setText(Double.toString(rs.getDouble(4)));
                txtTest2.setText(Double.toString(rs.getDouble(5)));
                txtAssignment.setText(Double.toString(rs.getDouble(6)));
                txtProject.setText(Double.toString(rs.getDouble(7)));

            }
            else{
                rs.previous();
                JOptionPane.showMessageDialog(AddFinalMarks.this, "End of file", "MarkBook", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(AddFinalMarks.this, e.getMessage());
        }

    }//GEN-LAST:event_cmdNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdFirst;
    private javax.swing.JButton cmdLast;
    private javax.swing.JButton cmdNext;
    private javax.swing.JButton cmdPrev;
    private javax.swing.JButton cmdUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField paper1;
    private javax.swing.JTextField paper2;
    private javax.swing.JTextField txtAssignment;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtProject;
    private javax.swing.JTextField txtTest1;
    private javax.swing.JTextField txtTest2;
    // End of variables declaration//GEN-END:variables
}
