package MarkBookApp;

import java.awt.Button;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author khalil
 */
public class MainApplicationScreen extends javax.swing.JFrame {
    
    static boolean start;
    /**
     * Creates new form MainApplicationScreen
     */
    public MainApplicationScreen() {
        
        initComponents();
        setIcon();
        
    }
    
    public void setIcon(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("book2.png")));
        
    }

         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        addStudent = new javax.swing.JMenuItem();
        addSemesterMarks = new javax.swing.JMenuItem();
        addFinalMarks = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editMarks = new javax.swing.JMenuItem();
        deleteStudentMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        StudentListMenuItem = new javax.swing.JMenuItem();
        StudentReportMenuItem = new javax.swing.JMenuItem();
        About = new javax.swing.JMenu();
        AboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MarkBook v1.0");
        setBackground(new java.awt.Color(0, 102, 255));
        setIconImages(null);
        setName("MainFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(0, 102, 255));
        desktopPane.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MarkBookApp/book2.png"))); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(340, 170, 270, 270);

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/file1.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        addStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        addStudent.setMnemonic('o');
        addStudent.setText("Add Student");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });
        fileMenu.add(addStudent);

        addSemesterMarks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        addSemesterMarks.setMnemonic('s');
        addSemesterMarks.setText("Add Semester  Marks");
        addSemesterMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterMarksActionPerformed(evt);
            }
        });
        fileMenu.add(addSemesterMarks);

        addFinalMarks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        addFinalMarks.setMnemonic('a');
        addFinalMarks.setText("Add Final Marks");
        addFinalMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFinalMarksActionPerformed(evt);
            }
        });
        fileMenu.add(addFinalMarks);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/edit (1).png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        editMarks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        editMarks.setMnemonic('t');
        editMarks.setText("Edit Marks");
        editMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMarksActionPerformed(evt);
            }
        });
        editMenu.add(editMarks);

        deleteStudentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deleteStudentMenuItem.setMnemonic('y');
        deleteStudentMenuItem.setText("Delete Student Record");
        deleteStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteStudentMenuItem);

        menuBar.add(editMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/report.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Report");

        StudentListMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        StudentListMenuItem.setMnemonic('c');
        StudentListMenuItem.setText("Student List");
        StudentListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentListMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(StudentListMenuItem);

        StudentReportMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        StudentReportMenuItem.setMnemonic('a');
        StudentReportMenuItem.setText("Student Report");
        StudentReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentReportMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(StudentReportMenuItem);

        menuBar.add(helpMenu);

        About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/info (1).png"))); // NOI18N
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });

        AboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        AboutMenuItem.setText("About Page");
        AboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuItemActionPerformed(evt);
            }
        });
        About.add(AboutMenuItem);

        menuBar.add(About);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        //CREATE ADDSTUDENT FRAME AND ADD TO DESKTOPPANE
        AddStudent add = new AddStudent();
        desktopPane.add(add);
        add.show();
    }//GEN-LAST:event_addStudentActionPerformed

    private void addSemesterMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterMarksActionPerformed
        //CREATE SEMESTER MARKS FRAME AND ADD TO DESKTOPPANE
        AddSemesterMarks add = new AddSemesterMarks();
        desktopPane.add(add);
        add.show();
    }//GEN-LAST:event_addSemesterMarksActionPerformed

    private void addFinalMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFinalMarksActionPerformed
        //SHOW FINAL MARKS INTERNAL FRAME
         AddFinalMarks1 add = new AddFinalMarks1();
         desktopPane.add(add);
         add.show();
    }//GEN-LAST:event_addFinalMarksActionPerformed

    private void editMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMarksActionPerformed
        //SHOW EDIT MARKS SCREEN
        EditMarks em = new EditMarks();
        desktopPane.add(em);
        em.show();
    }//GEN-LAST:event_editMarksActionPerformed

    private void deleteStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentMenuItemActionPerformed
        Delete del = new Delete();
        desktopPane.add(del);
        del.show();
    }//GEN-LAST:event_deleteStudentMenuItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               
    }//GEN-LAST:event_formWindowOpened

    private void StudentListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentListMenuItemActionPerformed
        StudentList list = new StudentList();
        desktopPane.add(list);
        list.show();
    }//GEN-LAST:event_StudentListMenuItemActionPerformed

    private void StudentReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentReportMenuItemActionPerformed
           
        StudentReportScreen src = new StudentReportScreen();
        desktopPane.add(src);
        src.show();
        
    }//GEN-LAST:event_StudentReportMenuItemActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutActionPerformed

    private void AboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuItemActionPerformed
        AboutScreen abt = new AboutScreen();
        desktopPane.add(abt);
        abt.show();
    }//GEN-LAST:event_AboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApplicationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApplicationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApplicationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplicationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    Thread.sleep(4500);
                }
                catch(Exception e){
                    
                }
                
                new MainApplicationScreen().setVisible(true);
                //Login log = new Login();
                //log.setVisible(true);
                                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JMenuItem StudentListMenuItem;
    private javax.swing.JMenuItem StudentReportMenuItem;
    private javax.swing.JMenuItem addFinalMarks;
    private javax.swing.JMenuItem addSemesterMarks;
    private javax.swing.JMenuItem addStudent;
    private javax.swing.JMenuItem deleteStudentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem editMarks;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
