/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MarkBookApp;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author khalil
 */
public class StudentReportScreen extends javax.swing.JInternalFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
    /**
     * Creates new form StudentReportScreen
     */
    public StudentReportScreen() {
        initComponents();
        getContentPane().setBackground(new Color(0, 105, 255));
        
    }

    public void ViewReport(){
        try {
            JasperReport report = JasperCompileManager.compileReport("C:\\Users\\khalil\\Dropbox\\School year 2\\Oops\\NetBeansWorkspace\\MarkBook\\src\\Reports\\StudentReport.jrxml");

            JasperPrint jasperPrint = JasperFillManager.fillReport(report, null, con);

            this.getContentPane().add(new JRViewer(jasperPrint));

        }  
        catch(Exception e){
            JOptionPane.showMessageDialog(StudentReportScreen.this, e.getMessage());
        }
        
        /*
        try{
           String report = "F:\\School year 2\\Oops\\NetBeansWorkspace\\MarkBook\\src\\Reports\\StudentReport.jrxml";
           JasperReport jr = JasperCompileManager.compileReport(report);
           JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
           JasperViewer.viewReport(jp);
        }   
        catch(Exception e){
            JOptionPane.showMessageDialog(StudentReportScreen.this, e.getMessage());
        }
        */
    }
    
    public void DoConnect(){
        
        try{
            //CONNECT TO DATABASE
            String user = "tutor";
            String password = "tutorAdmin";
            String url = "jdbc:derby://localhost:1527/students";
            
            con = DriverManager.getConnection(url, user, password);
            
            //EXECUTE SOME SQL AND LOAD THE RECORDS INTO THE RESULT SET
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT * FROM coursemarks";
            rs = stmt.executeQuery(sql);
            
            //SET CURSOR
            rs.first();
        }
        catch(SQLException e){ //CREATES OBJECT CALLED "E"
            JOptionPane.showMessageDialog(StudentReportScreen.this, e.getMessage());
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmdSR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdFR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmdClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Student Report");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/MarkBookApp/book2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("This is the Student Report Menu.");

        cmdSR.setBackground(new java.awt.Color(0, 153, 255));
        cmdSR.setForeground(new java.awt.Color(255, 255, 255));
        cmdSR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/report.png"))); // NOI18N
        cmdSR.setText("Student Report");
        cmdSR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        cmdSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSRActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setLabelFor(cmdSR);
        jLabel2.setText("<html> \"FINAL Student Report\" screen -<br/> Opens an individual student's report<html>");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setLabelFor(cmdSR);
        jLabel3.setText("<html> \"Student Report\" screen - <br/> Opens the report to browse all students<html>");

        cmdFR.setBackground(new java.awt.Color(0, 153, 255));
        cmdFR.setForeground(new java.awt.Color(255, 255, 255));
        cmdFR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/report.png"))); // NOI18N
        cmdFR.setText("<html><center>Final Student<br/> Report</center></html>");
        cmdFR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        cmdFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFRActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>*N.B - MR BRANKER YOU MIGHT HAVE TO CHANGE THE FILE PATH<br/>  OF THE REPORT SO IT CAN SHOW ON YOUR COMPUTER.<br/>  MY FILE PATH WAS SET ACCORDING TO WHERE THE REPORT WAS STORED ON MY COMPUTER<br/></html>");

        cmdClose.setBackground(new java.awt.Color(0, 153, 255));
        cmdClose.setForeground(new java.awt.Color(255, 255, 255));
        cmdClose.setText("Close");
        cmdClose.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 154, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmdSR)
                                .addGap(55, 55, 55))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cmdFR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(cmdClose)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(cmdFR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdSR)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(cmdClose)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSRActionPerformed
        DoConnect();
        
        try {
            JasperReport report = JasperCompileManager.compileReport("C:\\Users\\khalil\\Dropbox\\School year 2\\Oops\\NetBeansWorkspace\\MarkBook\\src\\Reports\\StudentReport.jrxml");
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(report, null, con);
            
            JFrame frame = new JFrame("Student Report");
            frame.getContentPane().add(new JRViewer(jasperPrint));
            frame.pack();
            frame.setVisible(true);
            frame.setExtendedState(MAXIMIZED_BOTH);
            frame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("book2.png")));
            frame.getContentPane().setBackground(new java.awt.Color(0, 105, 255)); 
            
        } catch (JRException ex) {
            
            Logger.getLogger(MainApplicationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            con.close();
            stmt.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(MainApplicationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdSRActionPerformed

    private void cmdFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFRActionPerformed
        FinalReport fr = new FinalReport();
        fr.setVisible(true);
    }//GEN-LAST:event_cmdFRActionPerformed

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdFR;
    private javax.swing.JButton cmdSR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
